# Documentation workflow - generates and deploys DocC documentation to GitHub Pages

name: Documentation
on:
  push:
    branches:
      - 'main'
jobs:
  build_docC:
    runs-on: macos-12
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
       repository: ${{ github.event.pull_request.head.repo.full_name }}
       ref: ${{ github.event.pull_request.head.ref }}

    - name: build static site
      uses: actions/build-docC-static-site@v1.0.2